Repository oracle/cluster-api-provider-oci, pull requests merged in 2022-04, with the labels that each got.

#44 feat: support multi region
  .gitignore
  Makefile
  api/v1beta1/ocicluster_types.go
  cloud/scope/clients.go
  cloud/scope/clients_mock.go
  cloud/scope/clients_test.go
  cloud/scope/cluster.go
  cloud/scope/vcn_reconciler.go
  cloud/services/networkloadbalancer/mock_nlb/client_mock.go
  config/crd/bases/infrastructure.cluster.x-k8s.io_ociclusters.yaml
  controllers/ocicluster_controller.go
  controllers/ocicluster_controller_test.go
  controllers/ocimachine_controller.go
  controllers/ocimachine_controller_test.go
  docs/src/gs/create-workload-cluster.md
  main.go
  scripts/ci-e2e.sh
  test/e2e/cluster_test.go
  test/e2e/config/e2e_conf.yaml
  test/e2e/data/infrastructure-oci/v1beta1/cluster-template-alternative-region.yaml
  test/e2e/data/infrastructure-oci/v1beta1/cluster-template-alternative-region/cluster.yaml
  test/e2e/data/infrastructure-oci/v1beta1/cluster-template-alternative-region/kustomization.yaml
  test/e2e/data/infrastructure-oci/v1beta1/cluster-template-alternative-region/md.yaml
  test/e2e/e2e_suite_test.go
Labels: enhancement

#52 docs: update workload cluster with multi-region support
  docs/build.sh
  docs/src/gs/create-workload-cluster.md
  templates/cluster-template-alternative-region.yaml
Labels: documentation

#58 docs: bump CAPOCI version to next release
  docs/src/gs/create-workload-cluster.md
  docs/src/gs/install-cluster-api.md
  metadata.yaml
Labels: documentation

#54 Add DRG based VCN peering
  Makefile
  api/v1beta1/conditions_consts.go
  api/v1beta1/ocicluster_types.go
  api/v1beta1/ociclustertemplate_types.go
  api/v1beta1/ocimachine_types.go
  api/v1beta1/ocimachinetemplate_types.go
  api/v1beta1/types.go
  api/v1beta1/zz_generated.deepcopy.go
  cloud/scope/cluster.go
  cloud/scope/cluster_client.go
  cloud/scope/drg_reconciler.go
  cloud/scope/drg_reconciler_test.go
  cloud/scope/drg_rpc_attachment_reconciler.go
  cloud/scope/drg_rpc_attachment_reconciler_test.go
  cloud/scope/drg_vcn_attachment_reconciler.go
  cloud/scope/drg_vcn_attachment_reconciler_test.go
  cloud/scope/mocks/cluster_client_mock.go
  cloud/scope/route_table_reconciler.go
  cloud/scope/vcn_reconciler_test.go
  cloud/services/vcn/client.go
  cloud/services/vcn/mock_vcn/client_mock.go
  config/crd/bases/infrastructure.cluster.x-k8s.io_ociclusters.yaml
  config/crd/bases/infrastructure.cluster.x-k8s.io_ociclustertemplates.yaml
  config/crd/bases/infrastructure.cluster.x-k8s.io_ocimachines.yaml
  config/crd/bases/infrastructure.cluster.x-k8s.io_ocimachinetemplates.yaml
  controllers/ocicluster_controller.go
  controllers/ocicluster_controller_test.go
  scripts/ci-e2e.sh
  templates/cluster-template-local-vcn-peering.yaml
  templates/cluster-template-remote-vcn.yaml
  test/README.md
  test/e2e/cluster_test.go
  test/e2e/config/e2e_conf.yaml
  test/e2e/data/ccm/ccm.yaml
  test/e2e/data/infrastructure-oci/v1beta1/cluster-template-ccm-testing/cluster.yaml
  test/e2e/data/infrastructure-oci/v1beta1/cluster-template-local-vcn-peering/cluster.yaml
  test/e2e/data/infrastructure-oci/v1beta1/cluster-template-local-vcn-peering/kustomization.yaml
  test/e2e/data/infrastructure-oci/v1beta1/cluster-template-remote-vcn-peering/cluster.yaml
  test/e2e/data/infrastructure-oci/v1beta1/cluster-template-remote-vcn-peering/kustomization.yaml
  test/e2e/data/infrastructure-oci/v1beta1/cluster-template-remote-vcn-peering/md.yaml
Labels: enhancement

#65 Add support for externally managed VCN
  Makefile
  api/v1beta1/types.go
  config/crd/bases/infrastructure.cluster.x-k8s.io_ociclusters.yaml
  config/crd/bases/infrastructure.cluster.x-k8s.io_ociclustertemplates.yaml
  controllers/ocicluster_controller.go
  controllers/ocicluster_controller_test.go
  docs/src/networking/custom-networking.md
  test/e2e/cluster_test.go
  test/e2e/config/e2e_conf.yaml
  test/e2e/data/infrastructure-oci/v1beta1/cluster-template-cluster-class/clusterclass-test-cluster-class.yaml
  test/e2e/data/infrastructure-oci/v1beta1/cluster-template-externally-managed-vcn/cluster.yaml
  test/e2e/data/infrastructure-oci/v1beta1/cluster-template-externally-managed-vcn/kustomization.yaml
Labels: enhancement

#74 Fix bug where clusterctl move does not work, and add correct default …
  api/v1beta1/ocicluster_types.go
  api/v1beta1/ocicluster_webhook.go
  api/v1beta1/ocicluster_webhook_test.go
  cloud/ociutil/ociutil.go
  cloud/ociutil/ociutil_test.go
  cloud/scope/cluster.go
  cloud/scope/drg_reconciler.go
  cloud/scope/drg_reconciler_test.go
  cloud/scope/drg_rpc_attachment_reconciler_test.go
  cloud/scope/drg_vcn_attachment_reconciler_test.go
  cloud/scope/internet_gateway_reconciler_test.go
  cloud/scope/load_balancer_reconciler.go
  cloud/scope/load_balancer_reconciler_test.go
  cloud/scope/machine.go
  cloud/scope/machine_test.go
  cloud/scope/nat_gateway_reconciler_test.go
  cloud/scope/nsg_reconciler_test.go
  cloud/scope/route_table_reconciler_test.go
  cloud/scope/security_list_reconciler_test.go
  cloud/scope/service_gateway_reconciler_test.go
  cloud/scope/subnet_reconciler_test.go
  cloud/scope/vcn_reconciler.go
  cloud/scope/vcn_reconciler_test.go
  config/crd/bases/infrastructure.cluster.x-k8s.io_ociclusters.yaml
  config/crd/bases/infrastructure.cluster.x-k8s.io_ociclustertemplates.yaml
  config/default/kustomization.yaml
  config/default/manager_pull_policy.yaml
  config/default/webhookcainjection_patch.yaml
  config/webhook/kustomizeconfig.yaml
  config/webhook/manifests.yaml
  controllers/ocicluster_controller.go
  controllers/ocicluster_controller_test.go
Labels: bug, enhancement

#68 Add documentation for private clusters and VCN peering
  docs/src/SUMMARY.md
  docs/src/networking/private-cluster.md
  templates/cluster-template-local-vcn-peering.yaml
  templates/cluster-template-remote-vcn-peering.yaml
Labels: documentation

#75 feat: update OCIMachineTemplate webhook validations
  api/v1beta1/ocimachinetemplate_webhook.go
  api/v1beta1/ocimachinetemplate_webhook_test.go
  api/v1beta1/validator.go
  templates/clusterclass-example.yaml
  test/e2e/data/infrastructure-oci/v1beta1/cluster-template-cluster-class/clusterclass-test-cluster-class.yaml
Labels: enhancement
