Repository oracle/cluster-api-provider-oci, pull requests merged in 2023-03, with the labels that each got.

#220 Upgrade to Kubernetes 1.25
  Makefile
  templates/cluster-template-oci-addons.yaml
  test/e2e/config/e2e_conf.yaml
  test/e2e/data/ccm/ccm.yaml
  test/e2e/data/cni/calico
  test/e2e/data/infrastructure-oci/v1beta1/bases/ccm.yaml
  test/e2e/managed_cluster_test.go
Labels: OCA Verified

#221 Fix private managed template to have correct seclist and Subnect CIDR
  exp/api/v1beta1/constants.go
  templates/cluster-template-managed-private.yaml
Labels: bug, OCA Verified

#222 feat: Add windows support
  Makefile
  docs/src/SUMMARY.md
  docs/src/gs/create-windows-workload-cluster.md
  scripts/ci-e2e.sh
  templates/cluster-template-windows-calico.yaml
  test/e2e/cluster_test.go
  test/e2e/config/e2e_conf.yaml
  test/e2e/data/infrastructure-oci/v1beta1/cluster-template-windows-calico/kustomization.yaml
  test/e2e/data/infrastructure-oci/v1beta1/cluster-template-windows-calico/md.yaml
Labels: documentation, enhancement, OCA Verified

#223 Update metadata file to next release
  metadata.yaml
Labels: OCA Verified
