Repository oracle/cluster-api-provider-oci, pull requests merged in 2023-02, with the labels that each got.

#205 Add create vnic details
  Tiltfile
  api/v1beta1/conditions_consts.go
  api/v1beta1/ocimachine_types.go
  api/v1beta1/types.go
  api/v1beta1/zz_generated.deepcopy.go
  cloud/scope/machine.go
  cloud/scope/util.go
  cloud/scope/vnic_reconciler.go
  cloud/scope/vnic_reconciler_test.go
  cloud/services/compute/client.go
  cloud/services/compute/mock_compute/client_mock.go
  cloud/services/vcn/client.go
  cloud/services/vcn/mock_vcn/client_mock.go
  config/crd/bases/infrastructure.cluster.x-k8s.io_ocimachines.yaml
  config/crd/bases/infrastructure.cluster.x-k8s.io_ocimachinetemplates.yaml
  controllers/ocimachine_controller.go
  scripts/ci-e2e.sh
Labels: enhancement, OCA Verified

#204 Proposal for Cluster identity
  docs/proposals/20230117-cluster-level-identity.md
Labels: OCA Verified

#210 docs: Update create-workload-cluster.md
  docs/src/gs/create-workload-cluster.md
Labels: documentation, OCA Verified

#211 Add support for confidential compute
  api/v1beta1/types.go
  api/v1beta1/zz_generated.deepcopy.go
  cloud/scope/machine.go
  cloud/scope/machine_pool.go
  cloud/scope/machine_pool_test.go
  cloud/scope/machine_test.go
  config/crd/bases/infrastructure.cluster.x-k8s.io_ocimachinepools.yaml
  config/crd/bases/infrastructure.cluster.x-k8s.io_ocimachines.yaml
  config/crd/bases/infrastructure.cluster.x-k8s.io_ocimachinetemplates.yaml
  docs/src/gs/customize-worker-node.md
  go.mod
  go.sum
Labels: OCA Verified

#172 Add doc for OKE and bug fixes
  docs/src/SUMMARY.md
  docs/src/gs/create-workload-cluster.md
  docs/src/managed/boot-volume-expansion.md
  docs/src/managed/managedcluster.md
  docs/src/managed/networking.md
  exp/api/v1beta1/ocimanagedcluster_webhook.go
  exp/api/v1beta1/ocimanagedmachinepool_webhook_test.go
  templates/cluster-template-managed-flannel.yaml
  templates/cluster-template-managed-private.yaml
  templates/cluster-template-managed.yaml
Labels: OCA Verified

#213 Fix metadata file to next release
  metadata.yaml
Labels: OCA Verified

#184 Update the CAPI version in the e2e_conf.yaml
  test/e2e/config/e2e_conf.yaml
Labels: enhancement, OCA Verified

#217 Update to use gomega gmeasure
  test/e2e/conformance_test.go
Labels: OCA Verified

#216 Add support for lookup of nodepool image if not present
  cloud/scope/managed_machine_pool.go
  cloud/scope/managed_machine_pool_test.go
  cloud/services/containerengine/client.go
  cloud/services/containerengine/mock_containerengine/client_mock.go
  docs/src/managed/managedcluster.md
  exp/api/v1beta1/ocimanagedmachinepool_webhook.go
  exp/api/v1beta1/ocimanagedmachinepool_webhook_test.go
  templates/cluster-template-managed-flannel.yaml
  templates/cluster-template-managed-private.yaml
  templates/cluster-template-managed.yaml
  test/e2e/config/e2e_conf.yaml
  test/e2e/data/infrastructure-oci/v1beta1/cluster-template-managed/machine-pool.yaml
  test/e2e/data/shared/v1beta1/metadata.yaml
Labels: enhancement, OCA Verified

#218 docs: Update install-cluster-api.md with new version
  docs/src/gs/install-cluster-api.md
Labels: documentation, OCA Verified
