Repository oracle/cluster-api-provider-oci, pull requests merged in 2023-05, with the labels that each got.

#255 Update CAPI version to 1.4.2
  go.mod
  go.sum
Labels: OCA Verified

#257 Add options to customize leader election
  cloud/scope/load_balancer_reconciler.go
  cloud/scope/machine.go
  main.go
Labels: enhancement, OCA Verified

#258 Fix implicit aliasing and other errors
  api/v1beta1/conversion.go
  api/v1beta1/ocicluster_conversion.go
  cloud/config/config.go
  cloud/scope/clients_mock.go
  cloud/scope/machine.go
  cloud/scope/machine_pool.go
Labels: OCA Verified

#260 Fix LB reconciliation to support multiple NSG
  cloud/scope/load_balancer_reconciler.go
  cloud/scope/load_balancer_reconciler_test.go
  cloud/scope/network_load_balancer_reconciler.go
  cloud/scope/network_load_balancer_reconciler_test.go
Labels: bug, enhancement, OCA Verified

#250 feat: Add custom cert support
  api/v1beta2/ocicluster_types.go
  api/v1beta2/zz_generated.deepcopy.go
  cloud/scope/clients.go
  cloud/scope/clients_test.go
  cloud/util/util.go
  cloud/util/util_test.go
  config/crd/bases/infrastructure.cluster.x-k8s.io_ociclusters.yaml
  config/crd/bases/infrastructure.cluster.x-k8s.io_ociclustertemplates.yaml
  config/crd/bases/infrastructure.cluster.x-k8s.io_ocimanagedclusters.yaml
  config/crd/bases/infrastructure.cluster.x-k8s.io_ocimanagedclustertemplates.yaml
  test/e2e/e2e_suite_test.go
Labels: enhancement, OCA Verified

#266 Fix storage versions for api increment
  api/v1beta1/ocicluster_types.go
  api/v1beta2/doc.go
  api/v1beta2/ocicluster_types.go
  config/crd/bases/infrastructure.cluster.x-k8s.io_ociclusters.yaml
  config/crd/bases/infrastructure.cluster.x-k8s.io_ocimachinepools.yaml
  config/crd/bases/infrastructure.cluster.x-k8s.io_ocimanagedclustertemplates.yaml
  config/crd/bases/infrastructure.cluster.x-k8s.io_ocimanagedcontrolplanes.yaml
  config/crd/bases/infrastructure.cluster.x-k8s.io_ocimanagedcontrolplanetemplates.yaml
  config/crd/bases/infrastructure.cluster.x-k8s.io_ocimanagedmachinepooltemplates.yaml
  config/crd/kustomization.yaml
  exp/api/v1beta1/ocimachinepool_types.go
  exp/api/v1beta1/ocimanagedclustertemplate_types.go
  exp/api/v1beta1/ocimanagedcontrolplane_types.go
  exp/api/v1beta1/ocimanagedcontrolplanetemplate_types.go
  exp/api/v1beta1/ocimanagedmachinepooltemplate_types.go
  exp/api/v1beta2/doc.go
  exp/api/v1beta2/ocimachinepool_types.go
  exp/api/v1beta2/ocimanagedcluster_types.go
  exp/api/v1beta2/ocimanagedcontrolplane_types.go
  exp/api/v1beta2/ocimanagedmachinepool_types.go
Labels: OCA Verified

#267 Update the machineHealthCheck and advance docs
  docs/src/gs/advanced.md
  docs/src/gs/create-mhc-workload-cluster.md
Labels: documentation, OCA Verified

#268 Add support for oci cli metrics
  cloud/metrics/http_request_dispatcher_wrapper.go
  cloud/metrics/metrics.go
  cloud/scope/clients.go
  go.mod
  go.sum
Labels: OCA Verified

#271 Update metadata file to next release
  metadata.yaml
Labels: enhancement, OCA Verified

#272 docs: Add generated API references to our book
  api/v1beta1/doc.go
  api/v1beta1/groupversion_info.go
  api/v1beta2/doc.go
  api/v1beta2/groupversion_info.go
  docs/build.sh
  docs/src/SUMMARY.md
  docs/src/reference/api-reference.md
  docs/src/reference/v1beta1-api.md
  docs/src/reference/v1beta1-exp-api.md
  docs/src/reference/v1beta2-api.md
  docs/src/reference/v1beta2-exp-api.md
  exp/api/v1beta1/doc.go
  exp/api/v1beta2/doc.go
Labels: documentation, OCA Verified
