Repository oracle/cluster-api-provider-oci, pull requests merged in 2023-06, with the labels that each got.

#277 Handle nil pointer in Lb delete
  cloud/scope/machine.go
  cloud/scope/machine_test.go
Labels: OCA Verified

#274 Fix OKE policy in doc
  docs/src/gs/iam/iam-oke.md
Labels: OCA Verified

#282 Update KubeadmConfigTemplate version and CAPI version
  go.mod
  go.sum
  templates/cluster-template-alternative-region.yaml
  templates/cluster-template-antrea.yaml
  templates/cluster-template-arm-free-tier.yaml
  templates/cluster-template-failure-domain-spread.yaml
  templates/cluster-template-healthcheck.yaml
  templates/cluster-template-local-vcn-peering.yaml
  templates/cluster-template-machinepool.yaml
  templates/cluster-template-oci-addons.yaml
  templates/cluster-template-oraclelinux.yaml
  templates/cluster-template-remote-vcn-peering.yaml
  templates/cluster-template-windows-calico.yaml
  templates/cluster-template.yaml
  test/e2e/data/infrastructure-oci/v1beta1/bases/md.yaml
  test/e2e/data/infrastructure-oci/v1beta2/bases/md.yaml
  test/e2e/data/infrastructure-oci/v1beta2/cluster-template-machine-pool/machine-pool.yaml
  test/e2e/data/infrastructure-oci/v1beta2/cluster-template-multiple-node-nsg/md.yaml
  test/e2e/data/infrastructure-oci/v1beta2/cluster-template-oracle-linux/md.yaml
  test/e2e/data/infrastructure-oci/v1beta2/cluster-template-windows-calico/md.yaml
Labels: OCA Verified

#278 docs: update readme zoom link
  README.md
Labels: documentation, OCA Verified

#286 Add docs for LBaaS support
  docs/src/networking/custom-networking.md
Labels: OCA Verified

#285 Add node pool recycling
  Makefile
  cloud/scope/managed_control_plane.go
  cloud/scope/managed_control_plane_test.go
  cloud/scope/managed_machine_pool.go
  cloud/scope/managed_machine_pool_test.go
  cloud/scope/util.go
  config/crd/bases/infrastructure.cluster.x-k8s.io_ocimanagedmachinepools.yaml
  config/crd/bases/infrastructure.cluster.x-k8s.io_ocimanagedmachinepooltemplates.yaml
  exp/api/v1beta1/conversion.go
  exp/api/v1beta1/ocimanagedmachinepool_conversion.go
  exp/api/v1beta1/zz_generated.conversion.go
  exp/api/v1beta2/ocimanagedmachinepool_types.go
  exp/api/v1beta2/ocimanagedmachinepool_webhook.go
  exp/api/v1beta2/ocimanagedmachinepool_webhook_test.go
  exp/api/v1beta2/zz_generated.deepcopy.go
  exp/controllers/ocimanagedcluster_controlplane_controller_test.go
  go.mod
  go.sum
  test/e2e/config/e2e_conf.yaml
  test/e2e/data/infrastructure-oci/v1beta2/cluster-template-managed-node-recycling/cluster.yaml
  test/e2e/data/infrastructure-oci/v1beta2/cluster-template-managed-node-recycling/kustomization.yaml
  test/e2e/data/infrastructure-oci/v1beta2/cluster-template-managed-node-recycling/machine-pool.yaml
  test/e2e/e2e_suite_test.go
  test/e2e/managed_cluster_test.go
Labels: OCA Verified

#287 OKE addon support
  cloud/scope/managed_control_plane.go
  cloud/scope/managed_control_plane_test.go
  cloud/services/containerengine/client.go
  cloud/services/containerengine/mock_containerengine/client_mock.go
  config/crd/bases/infrastructure.cluster.x-k8s.io_ocimanagedcontrolplanes.yaml
  config/crd/bases/infrastructure.cluster.x-k8s.io_ocimanagedcontrolplanetemplates.yaml
  exp/api/v1beta1/conversion.go
  exp/api/v1beta1/ocimanagedcontrolplane_conversion.go
  exp/api/v1beta1/zz_generated.conversion.go
  exp/api/v1beta2/ocimanagedcontrolplane_types.go
  exp/api/v1beta2/zz_generated.deepcopy.go
  exp/controllers/ocimanagedcluster_controlplane_controller.go
  test/e2e/data/infrastructure-oci/v1beta2/cluster-template-managed-virtual/cluster.yaml
  test/e2e/e2e_suite_test.go
  test/e2e/managed_cluster_test.go
Labels: OCA Verified

#290 Add doc for OKE addons and node pool cycling
  docs/src/SUMMARY.md
  docs/src/managed/features.md
Labels: OCA Verified

#291 Add Subnet Id and NSG ID to machine spec
  api/v1beta1/conversion.go
  api/v1beta1/conversion_test.go
  api/v1beta1/types.go
  api/v1beta1/zz_generated.conversion.go
  api/v1beta2/types.go
  api/v1beta2/zz_generated.deepcopy.go
  cloud/scope/machine.go
  cloud/scope/machine_test.go
  config/crd/bases/infrastructure.cluster.x-k8s.io_ocimachinepools.yaml
  config/crd/bases/infrastructure.cluster.x-k8s.io_ocimachines.yaml
  config/crd/bases/infrastructure.cluster.x-k8s.io_ocimachinetemplates.yaml
  exp/api/v1beta1/zz_generated.conversion.go
Labels: OCA Verified

#292 Remove references to local API reference docs
  docs/src/SUMMARY.md
  docs/src/reference/api-reference.md
Labels: OCA Verified

#293 Add subnet id to machine spec(v0.9.0 branch)
  api/v1beta1/conversion.go
  api/v1beta1/conversion_test.go
  api/v1beta1/types.go
  api/v1beta1/zz_generated.conversion.go
  api/v1beta2/types.go
  api/v1beta2/zz_generated.deepcopy.go
  cloud/scope/machine.go
  cloud/scope/machine_test.go
  config/crd/bases/infrastructure.cluster.x-k8s.io_ocimachinepools.yaml
  config/crd/bases/infrastructure.cluster.x-k8s.io_ocimachines.yaml
  config/crd/bases/infrastructure.cluster.x-k8s.io_ocimachinetemplates.yaml
Labels: OCA Verified

#296 Update metadata to next release
  metadata.yaml
Labels: enhancement, OCA Verified
