Repository oracle/cluster-api-provider-oci, pull requests merged in 2025-08, with the labels that each got.

#439 bug: Check if nsg.ID is null
  cloud/scope/util.go
Labels: bug, OCA Verified

#440 Pointer check
  cloud/scope/load_balancer_reconciler.go
  cloud/scope/machine.go
  cloud/scope/machine_pool.go
  cloud/scope/managed_control_plane.go
  cloud/scope/managed_machine_pool.go
  cloud/scope/network_load_balancer_reconciler.go
  cloud/scope/nsg_reconciler.go
  cloud/scope/route_table_reconciler.go
  cloud/scope/security_list_reconciler.go
  cloud/scope/subnet_reconciler.go
  cloud/scope/util.go
  cloud/scope/virtual_machine_pool.go
Labels: OCA Verified

#441 Upgrade golangci-lint version and configured nilaway
  .custom-gcl.yml
  .golangci.yml
  Makefile
  test/e2e/config/e2e_conf.yaml
Labels: enhancement, OCA Verified
